config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  root "recipes#index"
end

app/models/direction.rb
class Direction < ActiveRecord::Base
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	has_many :ingredients
	has_many :directions

	accepts_nested_attributes_for :ingredients,
  															reject_if: proc { |attributes| attributes['name'].blank? },
  															allow_destroy: true
 	accepts_nested_attributes_for :directions,
  															reject_if: proc { |attributes| attributes['step'].blank? },
  															allow_destroy: true
									
	validates :title, :description, :image, :category, :presence=>true						
	has_attached_file :image, :styles => { :medium => "400x400",:large => "800x800>"}
  	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController


	def index
		@recipe = Recipe.all.order("created_at DESC")
	end

	def show
		@recipe = Recipe.find(params[:id])
	end

	def new
		@recipe=Recipe.new
	end

	def edit
		@recipe = Recipe.find(params[:id])
	end

	def create
		@recipe=Recipe.new(show_params)
		if @recipe.save
			flash[:notice] = "Successfully Created"
			redirect_to(:action=>'index')
		else
			render "new"
		end
	end

	def update
		@recipe = Recipe.find(params[:id])
		if @recipe.update_attributes(show_params)
			flash[:notice] = "Successfully updated." 
      		redirect_to(:action=>'index')
    	else
    		flash[:notice] = "Record not saved." 
    		render('edit')
    	end
	end

	def destroy
		@recipe = Recipe.find(params[:id])
		@recipe.destroy
		redirect_to root_path, notice: "Successfully deleted recipe"
	end

	private
	def show_params
		params.require(:recipe).permit(:title,:description,:image,:preparation,:category,
			ingredients_attributes: [:id, :name, :_destroy],
			descriptions_attributes: [:id, :step, :_destroy])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Receipe Menu Home</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#"> <%= "Love to eat" %></a>
    </div>
    <div>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Add Recipe', new_recipe_path %></li>
        <li><%= link_to 'Sign Out', root_path %></li>
      </ul>
    </div>
  </div>
</nav>

 <div class="container">
    <% flash.each do |name,msg| %>
      <%= content_tag :div, msg, class: "alert" %>
    <% end %>
    <%= yield %>
  </div>
<div id="footer">
  <div class="container">
    <p class="text-muted" style="color:white">Created by <a style="color:white;font: italic;" href="http://github.com/sudhanva" target="_blank">Sudhanva Shivangere</a></p>
  </div>
</div>
</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title Receipe Menu Home
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
%body
	%nav.navbar.navbar-default
		.container
			.navbar-brand= "Love to eat"
			%ul.nav.navbar-nav.navbar-right
				%li= link_to 'Add Recipe', new_recipe_path
				%li= link_to 'Sign Out', root_path
	.container
		- flash.each do |name,msg|
			= content_tag :div, msg, class: "alert"
		= yield




	

app/views/recipes/_direction_fields.html.erb
<div class="form-inline clearfix">
  <div class="nested-fields">
    <%= f.input :step, input_html: { class: 'form-input form-control' } %>
    <%= link_to_remove_association "Remove", f, class: "form-button btn btn-default" %>
  </div>
</div>

app/views/recipes/_form.html.erb
<%= simple_form_for @recipe, html: { multipart: true } do |f| %>
  <% if @recipe.errors.any? %>
    <div id="errors">
      <p>
        <%= @recipe.errors.count %>
        Prevented this recipe froms saving
      </p>
      <ul>
        <% @recipe.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="panel-body">
    <%= f.input :title, input_html: { class: 'form-control' } %>
    <%= f.input :description, input_html: { class: 'form-control' } %>
    <%= f.input :preparation, input_html: { class: 'form-control' } %>
    <%= f.input :category, :collection => ['South Indian','North Indian'],input_html: { class: 'form-control'} %>
    <%= f.input :image, input_html: { class: 'form-control' } %>
    <div class="row">
      <div class="col-md-6">
        <h3>Ingredients</h3>
        <div id="ingredients">
          <%= f.simple_fields_for :ingredients do |ingredient| %>
            <%= render 'ingredient_fields', f: ingredient %>
          <% end %>
          <div class="links">
            <%= link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn btn-default add-button" %>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <h3>Directions</h3>
        <div id="directions">
          <%= f.simple_fields_for :directions do |direction| %>
            <%= render 'direction_fields', f: direction %>
          <% end %>
          <div class="links">
            <%= link_to_add_association 'Add Directions', f, :directions, class: "btn btn-default add-button" %>
          </div>
        </div>
      </div>
   </div>
  </div>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/recipes/_ingredient_fields.html.erb
<div class="form-inline clearfix">
  <div class="nested-fields">
    <%= f.input :name, input_html: { class: 'form-input form-control' } %>
    <%= link_to_remove_association "Remove", f, class: "form-button btn btn-default" %>
  </div>
</div>

app/views/recipes/edit.html.erb
  <h1>Edit Recipe</h1>
  <%= render 'form'   %>
<%= link_to "Back", root_path, class: "btn btn-default" %>

app/views/recipes/edit.html.haml
%div
.background
	%h1 Edit Recipe

	= render 'form'  

= link_to "Back", root_path, class: "btn btn-default"

app/views/recipes/index.html.erb
<% @recipe.each_slice(3) do |recipes| %>
  <div class="row">
    <% recipes.each do |recipe| %>
      <div class="col-md-4">
        <div class="recipe">
          <div class="image_wrapper">
            <%= link_to recipe do %>
              <%= image_tag recipe.image.url(:medium) %>
            <% end %>
          </div>
          <h2><%= recipe.title %><br>(<%= recipe.category %>)</h2>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/recipes/index.html.haml
- @recipe.each_slice(3) do |recipes|
	.row
		- recipes.each do |recipe|
			.col-md-4
				.recipe
					.image_wrapper
						= link_to recipe do
							= image_tag recipe.image.url(:medium)
					%h2= recipe.title

app/views/recipes/new.html.erb
<div>
<div class="background">
  <h1>New Recipe</h1>
  <%= render 'form'   %>
</div>
<%= link_to "Back", root_path, class: "btn btn-default" %>
</div>

app/views/recipes/new.html.haml
%h1 New Recipe

= render 'form'

%br/

= link_to "Back", root_path, class: "btn btn-default"

app/views/recipes/show.html.erb
<div class="main_content">
  <div class="row" id="recipe_top">
    <div class="col-md-4">
      <%= image_tag @recipe.image.url(:medium), class: "recipe_image" %>
    </div>
    <div class="col-md-8">
      <div id="recipe_info">
        <h1>
          <%= @recipe.title %>
        </h1>
        <p class="description">
          <%= @recipe.description %>
        </p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div id="ingredients">
        <h2>Ingredients</h2>
        <ul>
          <% @recipe.ingredients.each do |ingredient| %>
            <li>
              <%= ingredient.name %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-md-6">
      <div id="directions">
        <h2>Directions</h2>
        <ul>
          <% @recipe.directions.each do |direction| %>
            <li>
              <%= direction.step %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= link_to "Back", root_path, class: "btn btn-default" %>
     
        <%= link_to "Edit", edit_recipe_path, class: "btn btn-default" %>
        <%= link_to "Delete", recipe_path, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-default" %>
    </div>
  </div>
</div>

app/views/recipes/show.html.haml
%div
.background
	.row
	.col-md-7
		
		%h1= @recipe.title
		%h4= @recipe.description
		%p{:style => "text-align:justify"}= @recipe.preparation
	.row
		.col-md-5
			.recipe
			.image_wrapper
				= image_tag @recipe.image.url(:medium, class: "image-recipe", :style => "padding-right: 15px;")
			%br
			= link_to "Back", root_path, class: "btn btn-default"
			= link_to "Edit", edit_recipe_path, class: "btn btn-default"
			= link_to "Delete", recipe_path, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-default"
			%br